site_name: Kurs Programowania Mikrokontrolerów
site_description: Kurs ESP32-C6 z Arduino IDE – od podstaw do systemów bezprzewodowych
site_author: AGH-AIOTA

docs_dir: course

theme:
  name: material
  language: pl
  font:
    text: Outfit
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.path
    - navigation.footer
    - content.code.copy
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Przełącz na tryb ciemny
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Przełącz na tryb jasny

plugins:
  - search
  - callouts

nav:
  - Start:
      - Mapa kursu: index.md
      - Teoria – czym jest mikrokontroler: start/teoria.md
      - Płytka ESP32-C6: start/sprzet.md
      - Konfiguracja środowiska i Wokwi: start/ide.md

  - Podstawy:
      - Przegląd modułu: podstawy/index.md
      - "Wstęp do IO: Cyfrowe wyjścia i wejścia": podstawy/cyfrowe.md
      - "Sygnały: PWM i ADC": podstawy/analogowe.md
      - "Serwomechanizmy": podstawy/serwa.md
      - "Czas i Przerwania": podstawy/czas_przerwania.md

  - Protokoły komunikacyjne:
      - Przegląd modułu: protokoly/index.md
      - "UART": protokoly/uart.md
      - "Magistrala I²C": protokoly/i2c.md
      - "Magistrala SPI": protokoly/spi.md
      - "Transmisja jednoprzewodowa": protokoly/onewire.md

  - Systemy operacyjne i pamięć:
      - Przegląd modułu: systemy/index.md
      - "Pamięć trwała (NVS)": systemy/nvs.md
      - "Sleep: zarządzanie energią": systemy/deepsleep.md
      - "FreeRTOS: Zadania, kolejki i notyfikacje": systemy/freertos.md

  - Technologie bezprzewodowe:
      - Przegląd modułu: bezprzewodowe/index.md
      - "Wi-Fi: Serwer i Klient": bezprzewodowe/wifi.md
      - "Bluetooth Low Energy (BLE)": bezprzewodowe/ble.md
      - "ESP-NOW: Komunikacja bezpośrednia": bezprzewodowe/espnow.md

  - Materiały:
      - Kod wzorcowy: materialy/kod_wzorcowy.md
      - Pinout ESP32-C6 DevKit: materialy/pinout.md
      - Zasoby i dokumentacja: materialy/zasoby.md

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/custom.css
